package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"restServer/graph/model"
	"time"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.NewTask) (*model.Task, error) {
	attachments := make([]*model.Attachment, 0, len(input.Attachments))
	for _, a := range input.Attachments {
		attachments = append(attachments, &model.Attachment{
			Name:     a.Name,
			Date:     a.Date,
			Contents: a.Contents,
		})
	}
	id := r.Store.CreateTask(input.Text, input.Tags, input.Due, attachments)
	task, err := r.Store.GetTask(id)
	if err != nil {
		return nil, err
	}
	return &task, nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (*bool, error) {
	err := r.Store.DeleteTask(id)
	if err != nil {
		return nil, err
	}
	success := true
	return &success, nil
}

// DeleteAllTasks is the resolver for the deleteAllTasks field.
func (r *mutationResolver) DeleteAllTasks(ctx context.Context) (*bool, error) {
	err := r.Store.DeleteAllTasks()
	if err != nil {
		return nil, err
	}
	success := true
	return &success, nil
}

// GetAllTasks is the resolver for the getAllTasks field.
func (r *queryResolver) GetAllTasks(ctx context.Context) ([]*model.Task, error) {
	println("RESOLVER DEBUG: GetAllTasks llamado")
	println("RESOLVER DEBUG: Store pointer:", r.Store)

	tasks, err := r.Store.GetAllTasks()
	if err != nil {
		println("RESOLVER DEBUG: Error al obtener tareas:", err.Error())
		return nil, err
	}

	println("RESOLVER DEBUG: Total tareas obtenidas:", len(tasks))

	result := make([]*model.Task, 0, len(tasks))
	for i := range tasks {
		task := tasks[i]
		result = append(result, &task)
	}
	return result, nil
}

// GetTask is the resolver for the getTask field.
func (r *queryResolver) GetTask(ctx context.Context, id string) (*model.Task, error) {
	task, err := r.Store.GetTask(id)
	if err != nil {
		return nil, err
	}
	return &task, nil
}

// GetTasksByTag is the resolver for the getTasksByTag field.
func (r *queryResolver) GetTasksByTag(ctx context.Context, tag string) ([]*model.Task, error) {
	println("RESOLVER DEBUG: GetTasksByTag llamado con tag:", tag)
	println("RESOLVER DEBUG: Store pointer:", r.Store)

	tasks, err := r.Store.GetTasksByTag(tag)
	if err != nil {
		println("RESOLVER DEBUG: Error al obtener tareas:", err.Error())
		return nil, err
	}

	println("RESOLVER DEBUG: Tareas obtenidas del store:", len(tasks))

	result := make([]*model.Task, 0, len(tasks))
	for i := range tasks {
		task := tasks[i]
		result = append(result, &task)
	}

	println("RESOLVER DEBUG: Tareas a retornar:", len(result))
	return result, nil
}

// GetTasksByDue is the resolver for the getTasksByDue field.
func (r *queryResolver) GetTasksByDue(ctx context.Context, due time.Time) ([]*model.Task, error) {
	y, m, d := due.Date()
	tasks, err := r.Store.GetTasksByDue(y, m, d)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Task, 0, len(tasks))
	for i := range tasks {
		task := tasks[i]
		result = append(result, &task)
	}
	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
