// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Attachment struct {
	Name     string    `json:"Name"`
	Date     time.Time `json:"Date"`
	Contents string    `json:"Contents"`
}

type Mutation struct {
}

type NewAttachment struct {
	Name     string    `json:"Name"`
	Date     time.Time `json:"Date"`
	Contents string    `json:"Contents"`
}

type NewTask struct {
	Text        string           `json:"Text"`
	Tags        []string         `json:"Tags,omitempty"`
	Due         time.Time        `json:"Due"`
	Attachments []*NewAttachment `json:"Attachments,omitempty"`
}

type Query struct {
	
}

type Task struct {
	ID          string        `json:"Id"`
	Text        string        `json:"Text"`
	Tags        []string      `json:"Tags,omitempty"`
	Due         time.Time     `json:"Due"`
	Attachments []*Attachment `json:"Attachments,omitempty"`
}
